const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const yaml = require('js-yaml');
const asar = require('@electron/asar');
const zlib = require('zlib');
const assert = require('assert/strict');
const pkg = require('../package.json');
const root = path.join(__dirname, '..');
const dist = path.join(root, 'dist');
const metadata = yaml.load(fs.readFileSync(path.join(dist, 'latest.yml'), 'utf8'));
const name = `WatchTwitch-Setup-${pkg.version}.exe`;
const installer = fs.readFileSync(path.join(dist, name));
const hash = crypto.createHash('sha512').update(installer).digest('base64');
assert.equal(metadata.version, pkg.version);
assert.equal(metadata.path, name);
assert.equal(metadata.files.length, 1);
assert.equal(metadata.files[0].url, name);
assert.equal(metadata.files[0].size, installer.length);
assert.equal(metadata.files[0].sha512, hash);
assert.equal(metadata.sha512, hash);
const blockmap = JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(dist, name + '.blockmap'))));
assert.ok(blockmap.files.length > 0);
for (const file of blockmap.files) assert.equal(file.sizes.length, file.checksums.length);
const archive = path.join(dist, 'win-unpacked/resources/app.asar');
const packaged = JSON.parse(asar.extractFile(archive, 'package.json'));
assert.equal(packaged.version, pkg.version);
for (const file of ['main.js', 'preload.js', 'renderer/notification.html', 'renderer/js/router.js', 'renderer/js/pages/farming-page.js']) {
  assert.equal(asar.extractFile(archive, path.normalize(file)).toString(), fs.readFileSync(path.join(root, file), 'utf8'), `Packaged source mismatch: ${file}`);
}
assert.ok(!asar.listPackage(archive).some(file => /^[/\\](tests|_archive)[/\\]/.test(file)));
const config = yaml.load(fs.readFileSync(path.join(dist, 'win-unpacked/resources/app-update.yml'), 'utf8'));
const previousConfig = yaml.load(fs.readFileSync(path.join(dist, 'audit-old-app-update.yml'), 'utf8'));
assert.deepEqual(config, previousConfig, 'Update feed/cache configuration changed');
assert.equal(pkg.build.appId, 'com.watchtwitch.app');
assert.equal(pkg.build.nsis.artifactName, '${productName}-Setup-${version}.${ext}');
assert.ok(metadata.releaseNotes.includes('## 🇷🇺 Что нового'));
assert.ok(metadata.releaseNotes.includes("## 🇬🇧 What's new"));
console.log('PASS release metadata, installer SHA-512/size, blockmap, packaged source, unchanged update feed and installer identity');
console.log(JSON.stringify({ version: metadata.version, installer: name, bytes: installer.length, sha512: hash }));
